# -*- coding: utf-8 -*-
"""backtester.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1hFRImyTT2Wfj3v7GAkdE0wlTCAy_B5
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from itertools import product

ticker = "AAPL"
df = yf.download(ticker, start="2018-01-01", end="2024-01-01")

# Fix for newer versions of yfinance which return multi-level columns
if isinstance(df.columns, pd.MultiIndex):
    df.columns = df.columns.get_level_values(0)

df = df[["Close"]].copy()
df["Market_Return"] = df["Close"].pct_change()

# Split into in-sample and out-of-sample
in_sample  = df["2018":"2021"].copy()
out_sample = df["2022":"2024"].copy()

print(f"In-sample rows:      {len(in_sample)}")
print(f"Out-of-sample rows:  {len(out_sample)}")

# Verify it looks correct
print(df.head())
print(df.dtypes)

def backtest(data, short_window, long_window):
    df = data.copy()

    if len(df) < long_window + 10:
        return None

    df["MA_short"] = df["Close"].rolling(short_window).mean()
    df["MA_long"]  = df["Close"].rolling(long_window).mean()
    df.dropna(inplace=True)

    df["Signal"] = (df["MA_short"] > df["MA_long"]).astype(int)
    df["Market_Return"]   = df["Close"].pct_change()
    df["Strategy_Return"] = df["Market_Return"] * df["Signal"].shift(1)
    df.dropna(inplace=True)

    # ── Guard: skip if strategy never trades ──────────────────
    if df["Strategy_Return"].std() == 0 or len(df) < 20:
        return None

    total_return  = (1 + df["Strategy_Return"]).prod() - 1
    annual_return = (1 + total_return) ** (252 / len(df)) - 1
    annual_vol    = df["Strategy_Return"].std() * np.sqrt(252)

    risk_free     = 0.04
    sharpe        = (annual_return - risk_free) / annual_vol

    cumulative    = (1 + df["Strategy_Return"]).cumprod()
    rolling_max   = cumulative.cummax()
    max_drawdown  = ((cumulative - rolling_max) / rolling_max).min()

    return {
        "short_window":  short_window,
        "long_window":   long_window,
        "total_return":  round(total_return, 4),
        "annual_return": round(annual_return, 4),
        "sharpe":        round(sharpe, 4),
        "max_drawdown":  round(max_drawdown, 4),
        "cumulative":    cumulative
    }

short_windows = range(5,  60,  5)
long_windows  = range(20, 210, 10)

results = []

for sw, lw in product(short_windows, long_windows):
    if sw >= lw:
        continue
    result = backtest(in_sample, sw, lw)
    if result:
        results.append(result)

# Sanity check before sorting
print(f"Valid combinations found: {len(results)}")
if len(results) == 0:
    print("ERROR: No valid results — check that Block 1 ran correctly")
else:
    results_df = pd.DataFrame([{k: v for k, v in r.items() if k != "cumulative"}
                                for r in results])
    results_df.sort_values("sharpe", ascending=False, inplace=True)

    print(f"\nTotal combinations tested: {len(results_df)}")
    print("\nTop 10 by Sharpe Ratio:")
    print(results_df.head(10).to_string(index=False))

pivot = results_df.pivot_table(
    index="short_window",
    columns="long_window",
    values="sharpe"
)

plt.figure(figsize=(14, 7))
plt.imshow(pivot, aspect="auto", cmap="RdYlGn", origin="lower")
plt.colorbar(label="Sharpe Ratio")
plt.xticks(range(len(pivot.columns)), pivot.columns, rotation=45)
plt.yticks(range(len(pivot.index)),   pivot.index)
plt.xlabel("Long Window")
plt.ylabel("Short Window")
plt.title("Sharpe Ratio Heatmap — In-Sample (2018–2021)\nGreen = better, Red = worse")
plt.tight_layout()
plt.show()

best    = results_df.iloc[0]
best_sw = int(best["short_window"])
best_lw = int(best["long_window"])

print(f"Best parameters:      MA_{best_sw} / MA_{best_lw}")
print(f"In-sample Sharpe:     {best['sharpe']}")

out_result = backtest(out_sample, best_sw, best_lw)

print(f"\nOut-of-sample Sharpe:        {out_result['sharpe']}")
print(f"Out-of-sample Total Return:  {out_result['total_return']*100:.2f}%")
print(f"Out-of-sample Max Drawdown:  {out_result['max_drawdown']*100:.2f}%")

bh_return = (1 + out_sample["Market_Return"]).prod() - 1
print(f"\nBuy & Hold Total Return (same period): {bh_return*100:.2f}%")

out_sample_clean = out_sample.dropna().copy()
bh_cumulative    = (1 + out_sample_clean["Market_Return"]).cumprod()

fig, ax = plt.subplots(figsize=(14, 5))
ax.plot(bh_cumulative,            label="Buy & Hold", linewidth=1.5)
ax.plot(out_result["cumulative"], label=f"MA_{best_sw}/{best_lw} Strategy", linewidth=1.5)
ax.set_title(f"Out-of-Sample Performance (2022–2024)\nOptimized parameters: MA_{best_sw}/{best_lw}")
ax.set_ylabel("Portfolio Value")
ax.legend()
plt.tight_layout()
plt.show()

