# -*- coding: utf-8 -*-
"""options.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fvNFJiUpvnafJJ8_JVenuu8pWdULwSSr
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ticker = "AAPL"
df = yf.download(ticker, start="2018-01-01", end="2024-01-01")

if isinstance(df.columns, pd.MultiIndex):
  df.columns = df.columns.get_level_values(0)

df = df[["Close"]].copy()
df["Market_Return"] = df["Close"].pct_change()
df.dropna(inplace=True)

#Use the best parameters we found in Step 3
SHORT_WINDOW = 5
LONG_WINDOW = 20
INITIAL_CAPITAL = 100_000   # start with $100,000
COMMISSION = 0.001          # 0.1% per trade
POSITION_SIZE = 0.95        # invest 95% of available capital

print(f"Data loaded: {len(df)} rows")
print(df.head())

df["MA_short"] = df["Close"].rolling(SHORT_WINDOW).mean()
df["MA_long"] = df["Close"].rolling(LONG_WINDOW).mean()
df.dropna(inplace=True)

#Signal: 1 = invest, 0 = cash
df["Signal"] = (df["MA_short"] > df["MA_long"]).astype(int)

# Detect actual trade events (signal changes)
# diff() = 1 means signal flipped from 0→1 (BUY)
# diff() = -1 means signal flipped from 1→0 (SELL)
df["Trade"] = df["Signal"].diff().fillna(0)

buys = df[df["Trade"] == 1]
sells = df[df["Trade"] == -1]

print(f"Total buy signals:  {len(buys)}")
print(f"Total sell signals: {len(sells)}")
print(f"In market: {df['Signal'].mean()*100:.1f}% of the time")

# ── Portfolio state ───────────────────────────────────────────
cash        = INITIAL_CAPITAL
shares      = 0
portfolio_value = []
trade_log   = []

for date, row in df.iterrows():
    price  = row["Close"]
    signal = row["Signal"]
    trade  = row["Trade"]

    # ── BUY signal ────────────────────────────────────────────
    if trade == 1 and cash > 0:
      # How much capital to deploy
      capital_to_invest  = cash * POSITION_SIZE

      # Apply comission BEFORE buying
      commission_cost = capital_to_invest * COMMISSION
      capital_after_fee = capital_to_invest - commission_cost

      # How many shares can we buy?
      shares_bought = capital_after_fee / price
      shares += shares_bought
      cash -= capital_to_invest     # deduct full amount from cash

      trade_log.append({
          "date":       date,
          "action":     "BUY",
          "price":      round(price, 2),
          "shares":     round(shares_bought, 4),
          "commission": round(commission_cost, 2),
          "cash_after": round(cash, 2)
      })

    # ── SELL signal ───────────────────────────────────────────
    elif trade == -1 and shares > 0:
      # Gross proceeds from selling all shares
      gross_proceeds = shares * price

      # Apply commission After selling
      commission_cost = gross_proceeds * COMMISSION
      net_proceeds = gross_proceeds - commission_cost

      cash += net_proceeds
      shares = 0    # fully exit position

      trade_log.append({
          "date":       date,
          "action":     "SELL",
          "price":      round(price, 2),
          "shares":     round(gross_proceeds / price, 4),
          "commission": round(commission_cost, 2),
          "cash_after": round(cash, 2)
      })

    # ── Daily portfolio value ─────────────────────────────────
    # Value = cash on hand + current market value of shares held
    total_value = cash + (shares * price)
    portfolio_value.append({"date": date, "value": total_value})

# Convert to DataFrames
portfolio_df = pd.DataFrame(portfolio_value).set_index("date")
trade_log_df = pd.DataFrame(trade_log)

print(f"Final portfolio value: ${portfolio_df['value'].iloc[-1]:,.2f}")
print(f"Total trades executed: {len(trade_log_df)}")
print(f"\nTrade log (first 10):")
print(trade_log_df.head(10).to_string(index=False))

def performance_metrics(returns, label):
    total_return  = (1 + returns).prod() - 1
    annual_return = (1 + total_return) ** (252 / len(returns)) - 1
    annual_vol    = returns.std() * np.sqrt(252)
    risk_free     = 0.04
    sharpe        = (annual_return - risk_free) / annual_vol if annual_vol > 0 else 0

    cumulative  = (1 + returns).cumprod()
    rolling_max = cumulative.cummax()
    max_drawdown = ((cumulative - rolling_max) / rolling_max).min()

    print(f"\n── {label} ──")
    print(f"Total Return:    {total_return*100:.2f}%")
    print(f"Annual Return:   {annual_return*100:.2f}%")
    print(f"Annual Vol:      {annual_vol*100:.2f}%")
    print(f"Sharpe Ratio:    {sharpe:.3f}")
    print(f"Max Drawdown:    {max_drawdown*100:.2f}%")

# Strategy returns derived from portfolio value
portfolio_df["Strategy_Return"] = portfolio_df["value"].pct_change().dropna()

performance_metrics(df["Market_Return"],                   "Buy & Hold AAPL")
performance_metrics(portfolio_df["Strategy_Return"].dropna(), "MA Crossover (with costs)")

# Total commission paid
total_commission = trade_log_df["commission"].sum()
print(f"\nTotal commission paid: ${total_commission:,.2f}")

# Normalise both to start at 1.0 for fair comparison
bh_cumulative       = (1 + df["Market_Return"]).cumprod()
strategy_cumulative = portfolio_df["value"] / INITIAL_CAPITAL

fig, axes = plt.subplots(2, 1, figsize=(14, 10))

# Chart 1: Portfolio growth
axes[0].plot(bh_cumulative,       label="Buy & Hold",              linewidth=1.5)
axes[0].plot(strategy_cumulative, label="MA Crossover (with costs)", linewidth=1.5)
axes[0].set_title("Portfolio Growth: Strategy vs Buy & Hold (with transaction costs)")
axes[0].set_ylabel("Portfolio Value (starting at 1.0)")
axes[0].legend()

# Chart 2: Price with buy/sell signals
axes[1].plot(df["Close"], label="Price", linewidth=1, alpha=0.6)
axes[1].plot(df["MA_short"], label=f"MA_{SHORT_WINDOW}", linewidth=1.2, linestyle="--")
axes[1].plot(df["MA_long"],  label=f"MA_{LONG_WINDOW}",  linewidth=1.2, linestyle="--")

if len(trade_log_df) > 0:
    buys_log  = trade_log_df[trade_log_df["action"] == "BUY"]
    sells_log = trade_log_df[trade_log_df["action"] == "SELL"]
    axes[1].scatter(buys_log["date"],  buys_log["price"],
                    marker="^", color="green", s=100, label="Buy",  zorder=5)
    axes[1].scatter(sells_log["date"], sells_log["price"],
                    marker="v", color="red",   s=100, label="Sell", zorder=5)

axes[1].set_title("Buy & Sell Signals on Price Chart")
axes[1].legend()

plt.tight_layout()
plt.show()

