# -*- coding: utf-8 -*-
"""stock_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P-VHbXPUy2xq_89rD9_ow49E0Ew-K9iR
"""

!pip install yfinance

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ── 1. DOWNLOAD DATA ──────────────────────────────────────────
ticker = "AAPL"
df = yf.download(ticker, start="2022-01-01", end="2024-01-01")

print(df.head())        # first 5 rows
print(df.shape)         # how many rows/columns

# ── 2. CLEAN & EXPLORE ────────────────────────────────────────
print("\nMissing values:\n", df.isnull().sum())   # check for gaps
print("\nBasic stats:\n", df["Close"].describe())  # mean, std, min, max

# ── 3. COMPUTE INDICATORS ─────────────────────────────────────
# Moving averages: smooth out noise to reveal trends
df["MA_20"]  = df["Close"].rolling(window=20).mean()   # 50-day average
df["MA_100"] = df["Close"].rolling(window=100).mean()  # 200-day average

# Daily returns: % change day over day
df["Daily_Return"] = df["Close"].pct_change()

# Volatility: std of returns over 30-day rolling window
df["Volatility_30"] = df["Daily_Return"].rolling(window=30).std()

print("\nAnnualised Volatility:", round(df["Daily_Return"].std() * np.sqrt(252), 4))

# ── 4. VISUALISE ──────────────────────────────────────────────
fig, axes = plt.subplots(3, 1, figsize=(14, 10))
fig.suptitle(f"{ticker} Analysis", fontsize=16)

# Chart 1: Price + Moving Averages
axes[0].plot(df["Close"],  label="Close Price", linewidth=1)
axes[0].plot(df["MA_20"],  label="20-day MA",   linewidth=1.5, linestyle="--")
axes[0].plot(df["MA_100"], label="100-day MA",  linewidth=1.5, linestyle="--")
axes[0].set_title("Price & Moving Averages")
axes[0].legend()

# Chart 2: Daily Returns
axes[1].plot(df["Daily_Return"], label="Daily Return", color="orange", linewidth=0.8)
axes[1].axhline(0, color="black", linewidth=0.5)
axes[1].set_title("Daily Returns")
axes[1].legend()

# Chart 3: Rolling Volatility
axes[2].plot(df["Volatility_30"], label="30-day Volatility", color="red", linewidth=1)
axes[2].set_title("Rolling 30-day Volatility")
axes[2].legend()

plt.tight_layout()
plt.savefig("aapl_analysis.png", dpi=150)
plt.show()

# Compare how fast each MA reacts to the same price data
fig, ax = plt.subplots(figsize=(14, 5))

ax.plot(df["Close"],  label="Close Price", linewidth=1, alpha=0.5)
ax.plot(df["Close"].rolling(20).mean(),  label="MA_20",  linewidth=1.5)
ax.plot(df["Close"].rolling(50).mean(),  label="MA_50",  linewidth=1.5)
ax.plot(df["Close"].rolling(200).mean(), label="MA_200", linewidth=1.5)

ax.set_title("MA Comparison — notice how MA_20 hugs price vs MA_200")
ax.legend()
plt.show()

