# -*- coding: utf-8 -*-
"""ma_crossover_strategy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hib5bGnOrz4tcg4eF5MmrvV29C1EJ_si
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Download data
ticker = "AAPL"
df = yf.download(ticker, start="2021-01-01", end="2023-06-01")
df = df[["Close"]].copy()  # keep only closing price

# Compute the two moving averages
df["MA_20"]  = df["Close"].rolling(20).mean()
df["MA_50"]  = df["Close"].rolling(50).mean()

# Drop rows where MAs aren't calculated yet (first 50 days)
df.dropna(inplace=True)

print(df.head())
print(f"Rows: {len(df)}")

# Signal: 1 = hold long (be invested), 0 = stay in cash
# When MA_20 > MA_50, short term momentum is up → be invested
df["Signal"] = 0
df.loc[df["MA_20"] > df["MA_50"], "Signal"] = 1

# See how often we're in vs out of the market
print(df["Signal"].value_counts())
print(f"In market: {df['Signal'].mean()*100:.1f}% of the time")

# Daily return of AAPL stock
df["Market_Return"] = df["Close"].pct_change()

# Strategy return: we only capture the market return on days we hold
# On days Signal=0, we're in cash so return is 0
# NOTE: shift(1) is critical — we use YESTERDAY's signal to trade TODAY
# This prevents lookahead bias (using future info to make past decisions)
df["Strategy_Return"] = df["Market_Return"] * df["Signal"].shift(1)

# Cumulative returns: turn daily % returns into portfolio growth
# e.g. [0.01, -0.02, 0.03] → [1.01, 0.9898, 1.0195]
df["Market_Cumulative"]   = (1 + df["Market_Return"]).cumprod()
df["Strategy_Cumulative"] = (1 + df["Strategy_Return"]).cumprod()

print(df[["Market_Return", "Strategy_Return",
          "Market_Cumulative", "Strategy_Cumulative"]].tail(10))

def performance_metrics(returns, label):
    total_return   = (1 + returns).prod() - 1
    annual_return  = (1 + total_return) ** (252 / len(returns)) - 1
    annual_vol     = returns.std() * np.sqrt(252)
    sharpe         = annual_return / annual_vol  # assumes risk-free rate ≈ 0

    # Max drawdown: biggest peak-to-trough drop
    cumulative     = (1 + returns).cumprod()
    rolling_max    = cumulative.cummax()
    drawdown       = (cumulative - rolling_max) / rolling_max
    max_drawdown   = drawdown.min()

    print(f"\n── {label} ──")
    print(f"Total Return:    {total_return*100:.2f}%")
    print(f"Annual Return:   {annual_return*100:.2f}%")
    print(f"Annual Vol:      {annual_vol*100:.2f}%")
    print(f"Sharpe Ratio:    {sharpe:.3f}")
    print(f"Max Drawdown:    {max_drawdown*100:.2f}%")

performance_metrics(df["Market_Return"].dropna(),   "Buy & Hold AAPL")
performance_metrics(df["Strategy_Return"].dropna(), "MA Crossover Strategy")

fig, axes = plt.subplots(2, 1, figsize=(14, 9))

# Chart 1: Portfolio growth
axes[0].plot(df["Market_Cumulative"],   label="Buy & Hold",       linewidth=1.5)
axes[0].plot(df["Strategy_Cumulative"], label="MA Crossover",     linewidth=1.5)
axes[0].set_title("Portfolio Growth: Strategy vs Buy & Hold")
axes[0].set_ylabel("Portfolio Value (starting at 1.0)")
axes[0].legend()

# Chart 2: Buy/sell signals on price chart
axes[1].plot(df["Close"], label="Price", linewidth=1, alpha=0.7)
axes[1].plot(df["MA_20"], label="MA_20", linewidth=1.2, linestyle="--")
axes[1].plot(df["MA_50"], label="MA_50", linewidth=1.2, linestyle="--")

# Mark the exact buy and sell points
buy_signals  = df[df["Signal"].diff() == 1]   # signal flipped from 0 to 1
sell_signals = df[df["Signal"].diff() == -1]  # signal flipped from 1 to 0

axes[1].scatter(buy_signals.index,  buy_signals["Close"],
                marker="^", color="green", s=100, label="Buy",  zorder=5)
axes[1].scatter(sell_signals.index, sell_signals["Close"],
                marker="v", color="red",   s=100, label="Sell", zorder=5)

axes[1].set_title("Buy & Sell Signals on Price Chart")
axes[1].legend()

plt.tight_layout()
plt.show()

